#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.0.{build}-{branch}

skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2015

clone_depth: 1

nuget:  
  disable_publish_on_pr: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: 6xkLOjqMWYtgzJs6Uaid0HFWRust/BKvGmx7Hz0l/H5m/vsN1AKrmB52/lveihaT

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

build_script:
- dotnet --info
- dotnet restore --no-cache
- dotnet build **/project.json --configuration Release --version-suffix %APPVEYOR_BUILD_NUMBER%
- dotnet pack src/Hystrix.Dotnet/project.json --configuration Release --no-build

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
- dotnet test test/Hystrix.Dotnet.UnitTests/project.json --configuration Release --no-build
- dotnet test test/Hystrix.Dotnet.AspNet.UnitTests/project.json --configuration Release --no-build
- dotnet test test/Hystrix.Dotnet.AspNetCore.UnitTests/project.json --configuration Release --no-build
- bash coverage.sh
- bash coveralls.sh

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: src/**/*.nupkg

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off  
